#377 Label prop override
ripe-tech/ripe-components-react-native pull request #346
Opened 2022-09-01 16:09 UTC by 3rdvision

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-robin-revamp/issues/377 |
| Decisions | - Allow label prop override for translations <br> - Pretty |

2022-09-02 09:34 UTC, joao-conde requested changes

2022-09-02 09:34 UTC, joao-conde commented on react/components/molecules/chat-message/chat-message.js
> +            repliesLabelPlural: PropTypes.string,
replyLabel e repliesLabel talvez?

2022-09-02 09:34 UTC, joao-conde commented on react/components/organisms/chat/chat.js
> +                    repliesLabelPlural: PropTypes.string,
Same as above

2022-09-02 09:34 UTC, joao-conde commented on react/components/organisms/profile/profile.js
> +            buttons: PropTypes.array,
Do we want to replace the entirety of the buttons? This is for localization later right? Why not, similar to the other components above, just have a shareContactText and signOutText?

2022-09-02 14:10 UTC, joao-conde approved these changes

2022-09-02 14:36 UTC, NFSS10 requested changes
Revert the SVG change

![imagem](https://user-images.githubusercontent.com/22588915/188172808-0e451250-06e8-41c4-94d0-701c241983ac.png)

2022-09-02 14:41 UTC, 3rdvision commented
> Revert the SVG change
> 
> ![imagem](https://user-images.githubusercontent.com/22588915/188172808-0e451250-06e8-41c4-94d0-701c241983ac.png)

Pretty did this...

2022-09-02 15:35 UTC, NFSS10 approved these changes

2022-09-03 08:08 UTC, joamag approved these changes

2022-09-03 08:08 UTC, merged